// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_C2SROOMENTERREQ_H_
#define FLATBUFFERS_GENERATED_C2SROOMENTERREQ_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 22 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 6,
             "Non-compatible flatbuffers version included");

struct C2S_ROOM_ENTER_REQ;
struct C2S_ROOM_ENTER_REQBuilder;

struct C2S_ROOM_ENTER_REQ FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef C2S_ROOM_ENTER_REQBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SIZE = 4,
    VT_CODE = 6,
    VT_ROOMNO = 8,
    VT_USERIDX = 10
  };
  int32_t size() const {
    return GetField<int32_t>(VT_SIZE, 0);
  }
  int32_t code() const {
    return GetField<int32_t>(VT_CODE, 0);
  }
  int32_t roomNo() const {
    return GetField<int32_t>(VT_ROOMNO, 0);
  }
  int32_t userIdx() const {
    return GetField<int32_t>(VT_USERIDX, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_SIZE, 4) &&
           VerifyField<int32_t>(verifier, VT_CODE, 4) &&
           VerifyField<int32_t>(verifier, VT_ROOMNO, 4) &&
           VerifyField<int32_t>(verifier, VT_USERIDX, 4) &&
           verifier.EndTable();
  }
};

struct C2S_ROOM_ENTER_REQBuilder {
  typedef C2S_ROOM_ENTER_REQ Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_size(int32_t size) {
    fbb_.AddElement<int32_t>(C2S_ROOM_ENTER_REQ::VT_SIZE, size, 0);
  }
  void add_code(int32_t code) {
    fbb_.AddElement<int32_t>(C2S_ROOM_ENTER_REQ::VT_CODE, code, 0);
  }
  void add_roomNo(int32_t roomNo) {
    fbb_.AddElement<int32_t>(C2S_ROOM_ENTER_REQ::VT_ROOMNO, roomNo, 0);
  }
  void add_userIdx(int32_t userIdx) {
    fbb_.AddElement<int32_t>(C2S_ROOM_ENTER_REQ::VT_USERIDX, userIdx, 0);
  }
  explicit C2S_ROOM_ENTER_REQBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<C2S_ROOM_ENTER_REQ> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<C2S_ROOM_ENTER_REQ>(end);
    return o;
  }
};

inline flatbuffers::Offset<C2S_ROOM_ENTER_REQ> CreateC2S_ROOM_ENTER_REQ(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t size = 0,
    int32_t code = 0,
    int32_t roomNo = 0,
    int32_t userIdx = 0) {
  C2S_ROOM_ENTER_REQBuilder builder_(_fbb);
  builder_.add_userIdx(userIdx);
  builder_.add_roomNo(roomNo);
  builder_.add_code(code);
  builder_.add_size(size);
  return builder_.Finish();
}

inline const C2S_ROOM_ENTER_REQ *GetC2S_ROOM_ENTER_REQ(const void *buf) {
  return flatbuffers::GetRoot<C2S_ROOM_ENTER_REQ>(buf);
}

inline const C2S_ROOM_ENTER_REQ *GetSizePrefixedC2S_ROOM_ENTER_REQ(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<C2S_ROOM_ENTER_REQ>(buf);
}

inline bool VerifyC2S_ROOM_ENTER_REQBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<C2S_ROOM_ENTER_REQ>(nullptr);
}

inline bool VerifySizePrefixedC2S_ROOM_ENTER_REQBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<C2S_ROOM_ENTER_REQ>(nullptr);
}

inline void FinishC2S_ROOM_ENTER_REQBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<C2S_ROOM_ENTER_REQ> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedC2S_ROOM_ENTER_REQBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<C2S_ROOM_ENTER_REQ> root) {
  fbb.FinishSizePrefixed(root);
}

#endif  // FLATBUFFERS_GENERATED_C2SROOMENTERREQ_H_
