// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_S2CROOMENTERNTY_H_
#define FLATBUFFERS_GENERATED_S2CROOMENTERNTY_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 22 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 6,
             "Non-compatible flatbuffers version included");

struct S2C_ROOM_ENTER_NTY;
struct S2C_ROOM_ENTER_NTYBuilder;

struct S2C_ROOM_ENTER_NTY FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef S2C_ROOM_ENTER_NTYBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SIZE = 4,
    VT_CODE = 6,
    VT_ROOMNO = 8,
    VT_USERIDX = 10
  };
  int32_t size() const {
    return GetField<int32_t>(VT_SIZE, 0);
  }
  int32_t code() const {
    return GetField<int32_t>(VT_CODE, 0);
  }
  int32_t roomNo() const {
    return GetField<int32_t>(VT_ROOMNO, 0);
  }
  int32_t userIdx() const {
    return GetField<int32_t>(VT_USERIDX, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_SIZE, 4) &&
           VerifyField<int32_t>(verifier, VT_CODE, 4) &&
           VerifyField<int32_t>(verifier, VT_ROOMNO, 4) &&
           VerifyField<int32_t>(verifier, VT_USERIDX, 4) &&
           verifier.EndTable();
  }
};

struct S2C_ROOM_ENTER_NTYBuilder {
  typedef S2C_ROOM_ENTER_NTY Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_size(int32_t size) {
    fbb_.AddElement<int32_t>(S2C_ROOM_ENTER_NTY::VT_SIZE, size, 0);
  }
  void add_code(int32_t code) {
    fbb_.AddElement<int32_t>(S2C_ROOM_ENTER_NTY::VT_CODE, code, 0);
  }
  void add_roomNo(int32_t roomNo) {
    fbb_.AddElement<int32_t>(S2C_ROOM_ENTER_NTY::VT_ROOMNO, roomNo, 0);
  }
  void add_userIdx(int32_t userIdx) {
    fbb_.AddElement<int32_t>(S2C_ROOM_ENTER_NTY::VT_USERIDX, userIdx, 0);
  }
  explicit S2C_ROOM_ENTER_NTYBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<S2C_ROOM_ENTER_NTY> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<S2C_ROOM_ENTER_NTY>(end);
    return o;
  }
};

inline flatbuffers::Offset<S2C_ROOM_ENTER_NTY> CreateS2C_ROOM_ENTER_NTY(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t size = 0,
    int32_t code = 0,
    int32_t roomNo = 0,
    int32_t userIdx = 0) {
  S2C_ROOM_ENTER_NTYBuilder builder_(_fbb);
  builder_.add_userIdx(userIdx);
  builder_.add_roomNo(roomNo);
  builder_.add_code(code);
  builder_.add_size(size);
  return builder_.Finish();
}

inline const S2C_ROOM_ENTER_NTY *GetS2C_ROOM_ENTER_NTY(const void *buf) {
  return flatbuffers::GetRoot<S2C_ROOM_ENTER_NTY>(buf);
}

inline const S2C_ROOM_ENTER_NTY *GetSizePrefixedS2C_ROOM_ENTER_NTY(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<S2C_ROOM_ENTER_NTY>(buf);
}

inline bool VerifyS2C_ROOM_ENTER_NTYBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<S2C_ROOM_ENTER_NTY>(nullptr);
}

inline bool VerifySizePrefixedS2C_ROOM_ENTER_NTYBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<S2C_ROOM_ENTER_NTY>(nullptr);
}

inline void FinishS2C_ROOM_ENTER_NTYBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<S2C_ROOM_ENTER_NTY> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedS2C_ROOM_ENTER_NTYBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<S2C_ROOM_ENTER_NTY> root) {
  fbb.FinishSizePrefixed(root);
}

#endif  // FLATBUFFERS_GENERATED_S2CROOMENTERNTY_H_
