// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_C2SPIDREQ_H_
#define FLATBUFFERS_GENERATED_C2SPIDREQ_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 22 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 6,
             "Non-compatible flatbuffers version included");

struct C2S_PID_REQ;
struct C2S_PID_REQBuilder;

struct C2S_PID_REQ FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef C2S_PID_REQBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SIZE = 4,
    VT_CODE = 6,
    VT_PID = 8
  };
  int32_t size() const {
    return GetField<int32_t>(VT_SIZE, 0);
  }
  int32_t code() const {
    return GetField<int32_t>(VT_CODE, 0);
  }
  int32_t pid() const {
    return GetField<int32_t>(VT_PID, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_SIZE, 4) &&
           VerifyField<int32_t>(verifier, VT_CODE, 4) &&
           VerifyField<int32_t>(verifier, VT_PID, 4) &&
           verifier.EndTable();
  }
};

struct C2S_PID_REQBuilder {
  typedef C2S_PID_REQ Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_size(int32_t size) {
    fbb_.AddElement<int32_t>(C2S_PID_REQ::VT_SIZE, size, 0);
  }
  void add_code(int32_t code) {
    fbb_.AddElement<int32_t>(C2S_PID_REQ::VT_CODE, code, 0);
  }
  void add_pid(int32_t pid) {
    fbb_.AddElement<int32_t>(C2S_PID_REQ::VT_PID, pid, 0);
  }
  explicit C2S_PID_REQBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<C2S_PID_REQ> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<C2S_PID_REQ>(end);
    return o;
  }
};

inline flatbuffers::Offset<C2S_PID_REQ> CreateC2S_PID_REQ(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t size = 0,
    int32_t code = 0,
    int32_t pid = 0) {
  C2S_PID_REQBuilder builder_(_fbb);
  builder_.add_pid(pid);
  builder_.add_code(code);
  builder_.add_size(size);
  return builder_.Finish();
}

inline const C2S_PID_REQ *GetC2S_PID_REQ(const void *buf) {
  return flatbuffers::GetRoot<C2S_PID_REQ>(buf);
}

inline const C2S_PID_REQ *GetSizePrefixedC2S_PID_REQ(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<C2S_PID_REQ>(buf);
}

inline bool VerifyC2S_PID_REQBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<C2S_PID_REQ>(nullptr);
}

inline bool VerifySizePrefixedC2S_PID_REQBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<C2S_PID_REQ>(nullptr);
}

inline void FinishC2S_PID_REQBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<C2S_PID_REQ> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedC2S_PID_REQBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<C2S_PID_REQ> root) {
  fbb.FinishSizePrefixed(root);
}

#endif  // FLATBUFFERS_GENERATED_C2SPIDREQ_H_
